### ISSUE TITLE
using functions defined in module rather than from alga package

### ISSUE THREAD

**Issue by jitwit** [haskell-perf/graphs#13]
Hi. It seems like conversion to AIM and `reachable` are both defined in the benchmark module instead of using the implementations in alga:

[https://github.com/haskell-perf/graphs/blob/master/bench/Alga/Graph.hs](https://github.com/haskell-perf/graphs/blob/master/bench/Alga/Graph.hs)

**Comment by nobrakal** [comment]
This is corrected, thanks for the catch !
